post http://127.0.0.1:8000/api/create-session/
Content-Type: application/json

{
  "name": "Costel",
  "color": "#12345678"
}

###
post http://127.0.0.1:8000/api/join-session/
Content-Type: application/json

{
  "name": "cristi",
  "code": "2855"

}

###
post http://127.0.0.1:8000/api/start-session/
Content-Type: application/json

{
  "code": "1831"
}

###
post http://127.0.0.1:8000/api/end-session/
Content-Type: application/json

{
  "code": "1831"
}

###
post http://127.0.0.1:8000/api/find-location/
Content-Type: application/json

{
  "latitude": 44.41899784481032,
  "longitude": 26.023442594619166,
  "player_id": 9
}


###
get http://127.0.0.1:8000/api/test/

