# Generated by Django 3.2 on 2022-11-29 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('coordinates', models.TextField(null=True)),
                ('population', models.IntegerField(default=10000)),
                ('soldiers', models.IntegerField(default=100)),
                ('factories', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('money', models.IntegerField(default=1500)),
                ('owner', models.BooleanField(default=False)),
                ('color', models.CharField(default='#3aeb34', max_length=9)),
                ('soldiers', models.IntegerField(default=0)),
                ('push_token', models.CharField(max_length=255, null=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(default=10000)),
                ('soldiers', models.IntegerField(default=100)),
                ('factories', models.IntegerField(default=3)),
                ('game_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.gamesession')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.land')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.player')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='GameRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_price', models.IntegerField(default=100)),
                ('factory_revenue', models.IntegerField(default=10)),
                ('factory_limit', models.IntegerField(default=50)),
                ('population_rate', models.FloatField(default=0.05)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gamesession')),
            ],
            options={
                'verbose_name_plural': 'Game rules',
            },
        ),
    ]
