# Generated by Django 3.2 on 2022-08-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
