# Generated by Django 4.0.6 on 2022-07-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_gamesession_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='neighbourHood',
            new_name='neighbourhood',
        ),
        migrations.AddField(
            model_name='property',
            name='game_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.gamesession'),
        ),
    ]
