# Generated by Django 4.0.6 on 2022-07-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_neighbourhood_property_neighbourhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='coordinates',
            field=models.TextField(null=True),
        ),
    ]
