# Generated by Django 4.0.6 on 2022-07-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_property_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.CharField(default='#3aeb3444', max_length=9),
        ),
    ]
