# Generated by Django 4.0.6 on 2022-08-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_property_options_player_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(default='#3aeb34', max_length=9),
        ),
    ]
