# Generated by Django 4.0.6 on 2022-08-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_player_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeighbourHood',
            new_name='Land',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='neighbourhood',
            new_name='land',
        ),
    ]
