# Generated by Django 4.0.6 on 2022-08-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_neighbourhood_land_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
