# Generated by Django 4.0.6 on 2022-08-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_player_latitude_player_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='color',
        ),
        migrations.RemoveField(
            model_name='land',
            name='house_price',
        ),
        migrations.RemoveField(
            model_name='land',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='player',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='player',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='houses',
        ),
        migrations.AddField(
            model_name='land',
            name='factories',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='land',
            name='population',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='land',
            name='soldiers',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='soldiers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='factories',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='property',
            name='population',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='property',
            name='soldiers',
            field=models.IntegerField(default=100),
        ),
    ]
