# Generated by Django 4.0.6 on 2022-08-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_land_color_remove_land_house_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='push_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
