# Generated by Django 4.0.6 on 2022-08-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_player_push_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_price', models.IntegerField(default=100)),
                ('factory_output', models.IntegerField(default=10)),
                ('factory_limit', models.IntegerField(default=50)),
                ('population_rate', models.FloatField(default=0.05)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gamesession')),
            ],
            options={
                'verbose_name_plural': 'GameRules',
            },
        ),
    ]
